<?php
    if(isset($_POST['add'])) {
        $insert = sprintf("(`id`,`project_id`,`project_code`,`project_name`,`customer_name`,`service_type_implementation`,`service_type_maintenance`,`service_type_warranty`,`project_category`,`resource_level_1`,`resource_level_2`,`project_estimation_implementation`,`project_estimation_maintenance`,`project_estimation_warranty`,`amount_idr_implementation`,`amount_idr_maintenance`,`amount_idr_warranty`,`amount_usd_implementation`,`amount_usd_maintenance`,`amount_usd_warranty`,`bundling`,`mandays_implementation`,`mantotal_implementation`,`existing_bu_price`,`investment_bu_price`,`warranty_cisco_price`,`warranty_noncisco_price`,`implementation_price`,`maintenance_price`,`outsourcing_implementation_price`,`outsourcing_maintenance_price`,`addon_maintenance_price`,`bpd_price_implementation`,`bpd_price_maintenance`,`maintenance_package_price`,`mantotal_CR_implementation`,`mantotal_CR_maintenance`,`mantotal_CR_salespresales`,`mandays_value_CR_implementation`,`mandays_value_CR_maintenance`,`mandays_value_CR_salespresales`,`others_value_CR_implementation`,`others_value_CR_maintenance`,`others_value_CR_salespresales`,`task_category`,`resource_email`,`resource_role`,`duration_planning`,`start_date_plan`,`due_date_plan`,`jumlah_actual`,`start_actual`,`finish_actual`) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",
            GetSQLValueString($_POST['id'], "int"),
            GetSQLValueString($_POST['project_id'], "int"),
            GetSQLValueString($_POST['project_code'], "text"),
            GetSQLValueString($_POST['project_name'], "text"),
            GetSQLValueString($_POST['customer_name'], "text"),
            GetSQLValueString($_POST['service_type_implementation'], "int"),
            GetSQLValueString($_POST['service_type_maintenance'], "int"),
            GetSQLValueString($_POST['service_type_warranty'], "int"),
            GetSQLValueString($_POST['project_category'], "text"),
            GetSQLValueString($_POST['resource_level_1'], "int"),
            GetSQLValueString($_POST['resource_level_2'], "int"),
            GetSQLValueString($_POST['project_estimation_implementation'], "text"),
            GetSQLValueString($_POST['project_estimation_maintenance'], "text"),
            GetSQLValueString($_POST['project_estimation_warranty'], "text"),
            GetSQLValueString($_POST['amount_idr_implementation'], "decimal"),
            GetSQLValueString($_POST['amount_idr_maintenance'], "decimal"),
            GetSQLValueString($_POST['amount_idr_warranty'], "decimal"),
            GetSQLValueString($_POST['amount_usd_implementation'], "decimal"),
            GetSQLValueString($_POST['amount_usd_maintenance'], "decimal"),
            GetSQLValueString($_POST['amount_usd_warranty'], "decimal"),
            GetSQLValueString($_POST['bundling'], "text"),
            GetSQLValueString($_POST['mandays_implementation'], "decimal"),
            GetSQLValueString($_POST['mantotal_implementation'], "int"),
            GetSQLValueString($_POST['existing_bu_price'], "decimal"),
            GetSQLValueString($_POST['investment_bu_price'], "decimal"),
            GetSQLValueString($_POST['warranty_cisco_price'], "decimal"),
            GetSQLValueString($_POST['warranty_noncisco_price'], "decimal"),
            GetSQLValueString($_POST['implementation_price'], "decimal"),
            GetSQLValueString($_POST['maintenance_price'], "decimal"),
            GetSQLValueString($_POST['outsourcing_implementation_price'], "decimal"),
            GetSQLValueString($_POST['outsourcing_maintenance_price'], "decimal"),
            GetSQLValueString($_POST['addon_maintenance_price'], "decimal"),
            GetSQLValueString($_POST['bpd_price_implementation'], "decimal"),
            GetSQLValueString($_POST['bpd_price_maintenance'], "decimal"),
            GetSQLValueString($_POST['maintenance_package_price'], "decimal"),
            GetSQLValueString($_POST['mantotal_CR_implementation'], "int"),
            GetSQLValueString($_POST['mantotal_CR_maintenance'], "decimal"),
            GetSQLValueString($_POST['mantotal_CR_salespresales'], "decimal"),
            GetSQLValueString($_POST['mandays_value_CR_implementation'], "decimal"),
            GetSQLValueString($_POST['mandays_value_CR_maintenance'], "decimal"),
            GetSQLValueString($_POST['mandays_value_CR_salespresales'], "decimal"),
            GetSQLValueString($_POST['others_value_CR_implementation'], "decimal"),
            GetSQLValueString($_POST['others_value_CR_maintenance'], "decimal"),
            GetSQLValueString($_POST['others_value_CR_salespresales'], "decimal"),
            GetSQLValueString($_POST['task_category'], "text"),
            GetSQLValueString($_POST['resource_email'], "text"),
            GetSQLValueString($_POST['resource_role'], "text"),
            GetSQLValueString($_POST['duration_planning'], "decimal"),
            GetSQLValueString($_POST['start_date_plan'], "text"),
            GetSQLValueString($_POST['due_date_plan'], "text"),
            GetSQLValueString($_POST['jumlah_actual'], "double"),
            GetSQLValueString($_POST['start_actual'], "text"),
            GetSQLValueString($_POST['finish_actual'], "text")
        );
        $res = $DB->insert_data($tblname, $insert);
        $ALERT->savedata();
    } elseif(isset($_POST['save'])) {
        $condition = "id=" . $_POST['id'];
        $update = sprintf("`id`=%s,`project_id`=%s,`project_code`=%s,`project_name`=%s,`customer_name`=%s,`service_type_implementation`=%s,`service_type_maintenance`=%s,`service_type_warranty`=%s,`project_category`=%s,`resource_level_1`=%s,`resource_level_2`=%s,`project_estimation_implementation`=%s,`project_estimation_maintenance`=%s,`project_estimation_warranty`=%s,`amount_idr_implementation`=%s,`amount_idr_maintenance`=%s,`amount_idr_warranty`=%s,`amount_usd_implementation`=%s,`amount_usd_maintenance`=%s,`amount_usd_warranty`=%s,`bundling`=%s,`mandays_implementation`=%s,`mantotal_implementation`=%s,`existing_bu_price`=%s,`investment_bu_price`=%s,`warranty_cisco_price`=%s,`warranty_noncisco_price`=%s,`implementation_price`=%s,`maintenance_price`=%s,`outsourcing_implementation_price`=%s,`outsourcing_maintenance_price`=%s,`addon_maintenance_price`=%s,`bpd_price_implementation`=%s,`bpd_price_maintenance`=%s,`maintenance_package_price`=%s,`mantotal_CR_implementation`=%s,`mantotal_CR_maintenance`=%s,`mantotal_CR_salespresales`=%s,`mandays_value_CR_implementation`=%s,`mandays_value_CR_maintenance`=%s,`mandays_value_CR_salespresales`=%s,`others_value_CR_implementation`=%s,`others_value_CR_maintenance`=%s,`others_value_CR_salespresales`=%s,`task_category`=%s,`resource_email`=%s,`resource_role`=%s,`duration_planning`=%s,`start_date_plan`=%s,`due_date_plan`=%s,`jumlah_actual`=%s,`start_actual`=%s,`finish_actual`=%s",
            GetSQLValueString($_POST['id'], "int"),
            GetSQLValueString($_POST['project_id'], "int"),
            GetSQLValueString($_POST['project_code'], "text"),
            GetSQLValueString($_POST['project_name'], "text"),
            GetSQLValueString($_POST['customer_name'], "text"),
            GetSQLValueString($_POST['service_type_implementation'], "int"),
            GetSQLValueString($_POST['service_type_maintenance'], "int"),
            GetSQLValueString($_POST['service_type_warranty'], "int"),
            GetSQLValueString($_POST['project_category'], "text"),
            GetSQLValueString($_POST['resource_level_1'], "int"),
            GetSQLValueString($_POST['resource_level_2'], "int"),
            GetSQLValueString($_POST['project_estimation_implementation'], "text"),
            GetSQLValueString($_POST['project_estimation_maintenance'], "text"),
            GetSQLValueString($_POST['project_estimation_warranty'], "text"),
            GetSQLValueString($_POST['amount_idr_implementation'], "decimal"),
            GetSQLValueString($_POST['amount_idr_maintenance'], "decimal"),
            GetSQLValueString($_POST['amount_idr_warranty'], "decimal"),
            GetSQLValueString($_POST['amount_usd_implementation'], "decimal"),
            GetSQLValueString($_POST['amount_usd_maintenance'], "decimal"),
            GetSQLValueString($_POST['amount_usd_warranty'], "decimal"),
            GetSQLValueString($_POST['bundling'], "text"),
            GetSQLValueString($_POST['mandays_implementation'], "decimal"),
            GetSQLValueString($_POST['mantotal_implementation'], "int"),
            GetSQLValueString($_POST['existing_bu_price'], "decimal"),
            GetSQLValueString($_POST['investment_bu_price'], "decimal"),
            GetSQLValueString($_POST['warranty_cisco_price'], "decimal"),
            GetSQLValueString($_POST['warranty_noncisco_price'], "decimal"),
            GetSQLValueString($_POST['implementation_price'], "decimal"),
            GetSQLValueString($_POST['maintenance_price'], "decimal"),
            GetSQLValueString($_POST['outsourcing_implementation_price'], "decimal"),
            GetSQLValueString($_POST['outsourcing_maintenance_price'], "decimal"),
            GetSQLValueString($_POST['addon_maintenance_price'], "decimal"),
            GetSQLValueString($_POST['bpd_price_implementation'], "decimal"),
            GetSQLValueString($_POST['bpd_price_maintenance'], "decimal"),
            GetSQLValueString($_POST['maintenance_package_price'], "decimal"),
            GetSQLValueString($_POST['mantotal_CR_implementation'], "int"),
            GetSQLValueString($_POST['mantotal_CR_maintenance'], "decimal"),
            GetSQLValueString($_POST['mantotal_CR_salespresales'], "decimal"),
            GetSQLValueString($_POST['mandays_value_CR_implementation'], "decimal"),
            GetSQLValueString($_POST['mandays_value_CR_maintenance'], "decimal"),
            GetSQLValueString($_POST['mandays_value_CR_salespresales'], "decimal"),
            GetSQLValueString($_POST['others_value_CR_implementation'], "decimal"),
            GetSQLValueString($_POST['others_value_CR_maintenance'], "decimal"),
            GetSQLValueString($_POST['others_value_CR_salespresales'], "decimal"),
            GetSQLValueString($_POST['task_category'], "text"),
            GetSQLValueString($_POST['resource_email'], "text"),
            GetSQLValueString($_POST['resource_role'], "text"),
            GetSQLValueString($_POST['duration_planning'], "decimal"),
            GetSQLValueString($_POST['start_date_plan'], "text"),
            GetSQLValueString($_POST['due_date_plan'], "text"),
            GetSQLValueString($_POST['jumlah_actual'], "double"),
            GetSQLValueString($_POST['start_actual'], "text"),
            GetSQLValueString($_POST['finish_actual'], "text")
    );
        $res = $DB->update_data($tblname, $update, $condition);
        $ALERT->savedata();
    }
    ?>