<?php
    if(isset($_POST['add'])) {
        $insert = sprintf("(`email_id`,`id_request`,`id_fpkb`,`id_calendar`,`nama_kandidat`,`email`,`id_folderdrive`,`id_file`,`file`,`tanggal_interview`,`link_webex`,`pic`,`project_code`,`catatan`,`interview_user`,`interview_hcm`,`offering_salary`,`salary_Probation`,`salary_Permanent`,`manager_hcm`,`status_manager_hcm`,`catatan_manager_hcm`,`hcm_gm`,`status_hcm_gm`,`catatan_hcm_gm`,`gm_offering`,`status_gm_offering`,`catatan_gm_offering`,`bod`,`status_bod`,`catatan_bod`,`status_cv`,`join_date`,`status`) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",
            GetSQLValueString($_POST['email_id'], "int"),
            GetSQLValueString($_POST['id_request'], "text"),
            GetSQLValueString($_POST['id_fpkb'], "text"),
            GetSQLValueString($_POST['id_calendar'], "text"),
            GetSQLValueString($_POST['nama_kandidat'], "text"),
            GetSQLValueString($_POST['email'], "text"),
            GetSQLValueString($_POST['id_folderdrive'], "text"),
            GetSQLValueString($_POST['id_file'], "text"),
            GetSQLValueString($_POST['file'], "text"),
            GetSQLValueString($_POST['tanggal_interview'], "date"),
            GetSQLValueString($_POST['link_webex'], "text"),
            GetSQLValueString($_POST['pic'], "text"),
            GetSQLValueString($_POST['project_code'], "text"),
            GetSQLValueString($_POST['catatan'], "text"),
            GetSQLValueString($_POST['interview_user'], "text"),
            GetSQLValueString($_POST['interview_hcm'], "text"),
            GetSQLValueString($_POST['offering_salary'], "text"),
            GetSQLValueString($_POST['salary_Probation'], "text"),
            GetSQLValueString($_POST['salary_Permanent'], "text"),
            GetSQLValueString($_POST['manager_hcm'], "text"),
            GetSQLValueString($_POST['status_manager_hcm'], "text"),
            GetSQLValueString($_POST['catatan_manager_hcm'], "text"),
            GetSQLValueString($_POST['hcm_gm'], "text"),
            GetSQLValueString($_POST['status_hcm_gm'], "text"),
            GetSQLValueString($_POST['catatan_hcm_gm'], "text"),
            GetSQLValueString($_POST['gm_offering'], "text"),
            GetSQLValueString($_POST['status_gm_offering'], "text"),
            GetSQLValueString($_POST['catatan_gm_offering'], "text"),
            GetSQLValueString($_POST['bod'], "text"),
            GetSQLValueString($_POST['status_bod'], "text"),
            GetSQLValueString($_POST['catatan_bod'], "text"),
            GetSQLValueString($_POST['status_cv'], "text"),
            GetSQLValueString($_POST['join_date'], "date"),
            GetSQLValueString($_POST['status'], "text")
        );
        $res = $DB->insert_data($tblname, $insert);
        $ALERT->savedata();
    } elseif(isset($_POST['save'])) {
        $condition = "email_id=" . $_POST['email_id'];
        $update = sprintf("`email_id`=%s,`id_request`=%s,`id_fpkb`=%s,`id_calendar`=%s,`nama_kandidat`=%s,`email`=%s,`id_folderdrive`=%s,`id_file`=%s,`file`=%s,`tanggal_interview`=%s,`link_webex`=%s,`pic`=%s,`project_code`=%s,`catatan`=%s,`interview_user`=%s,`interview_hcm`=%s,`offering_salary`=%s,`salary_Probation`=%s,`salary_Permanent`=%s,`manager_hcm`=%s,`status_manager_hcm`=%s,`catatan_manager_hcm`=%s,`hcm_gm`=%s,`status_hcm_gm`=%s,`catatan_hcm_gm`=%s,`gm_offering`=%s,`status_gm_offering`=%s,`catatan_gm_offering`=%s,`bod`=%s,`status_bod`=%s,`catatan_bod`=%s,`status_cv`=%s,`join_date`=%s,`status`=%s",
            GetSQLValueString($_POST['email_id'], "int"),
            GetSQLValueString($_POST['id_request'], "text"),
            GetSQLValueString($_POST['id_fpkb'], "text"),
            GetSQLValueString($_POST['id_calendar'], "text"),
            GetSQLValueString($_POST['nama_kandidat'], "text"),
            GetSQLValueString($_POST['email'], "text"),
            GetSQLValueString($_POST['id_folderdrive'], "text"),
            GetSQLValueString($_POST['id_file'], "text"),
            GetSQLValueString($_POST['file'], "text"),
            GetSQLValueString($_POST['tanggal_interview'], "date"),
            GetSQLValueString($_POST['link_webex'], "text"),
            GetSQLValueString($_POST['pic'], "text"),
            GetSQLValueString($_POST['project_code'], "text"),
            GetSQLValueString($_POST['catatan'], "text"),
            GetSQLValueString($_POST['interview_user'], "text"),
            GetSQLValueString($_POST['interview_hcm'], "text"),
            GetSQLValueString($_POST['offering_salary'], "text"),
            GetSQLValueString($_POST['salary_Probation'], "text"),
            GetSQLValueString($_POST['salary_Permanent'], "text"),
            GetSQLValueString($_POST['manager_hcm'], "text"),
            GetSQLValueString($_POST['status_manager_hcm'], "text"),
            GetSQLValueString($_POST['catatan_manager_hcm'], "text"),
            GetSQLValueString($_POST['hcm_gm'], "text"),
            GetSQLValueString($_POST['status_hcm_gm'], "text"),
            GetSQLValueString($_POST['catatan_hcm_gm'], "text"),
            GetSQLValueString($_POST['gm_offering'], "text"),
            GetSQLValueString($_POST['status_gm_offering'], "text"),
            GetSQLValueString($_POST['catatan_gm_offering'], "text"),
            GetSQLValueString($_POST['bod'], "text"),
            GetSQLValueString($_POST['status_bod'], "text"),
            GetSQLValueString($_POST['catatan_bod'], "text"),
            GetSQLValueString($_POST['status_cv'], "text"),
            GetSQLValueString($_POST['join_date'], "date"),
            GetSQLValueString($_POST['status'], "text")
    );
        $res = $DB->update_data($tblname, $update, $condition);
        $ALERT->savedata();
    }
    ?>